server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/todolist?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


Logging:
  level:
    com.pms: debug
